#!/usr/bin/ruby

=begin
Adam Lathers
alathers@gmail.com


The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number 
would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?


=end

require '../lib-ruby/myInteger.rb'

=begin
divisorGoal=200
divisors=Array.new
triangleCounter=0
while divisors.length < divisorGoal do 
    triangleCounter+=1
    divisors=factor( triangleNum triangleCounter)
end
puts "#{triangleCounter} : " + triangleNum(triangleCounter).to_s
=end


i=1
limit=ARGV.shift || 500

until i.triangle.factor.length >= limit.to_i
    i+=1
    #puts "#{i} = #{i.triangle.factor.length}"
end
puts  "First  i = #{i}, whose triangle is #{i.triangle} with  #{i.triangle.factor.length} factors"